name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily
  workflow_dispatch:  # Allows you to run it manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: Platane/snk@v3
        with:
          github_user_name: Devashish0404
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.svg?palette=github-light
          
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output  # This creates the 'output' branch with your SVG file
          commit_message: "Generate snake animation"
